### ISSUE TITLE
Problem with naming during create_wcs in finalise_reduction

### ISSUE THREAD

**Issue by oegorov** [emsellem/pymusepipe#13]
Esorex creates files named P001 etc during the create_wcs step. Further reduction (create_expocubes) crashes because it correctly assumes that they should be named in OB001 etc style.

**Comment by emsellem** [comment]
Actually, I believe that P001 is the right thing. However, if it looks for OB001 that is where the problem lies.

The reference should always be with the Pointing not with the datasets (OBs)
I'll check why the sof file contains OB001, which makes no sense here since an OB can contain several pointings (and one pointing can contain several OBs).

**Comment by emsellem** [comment]
Ok I found the problem. Not an easy one. Will think about it and try to find an easy way forward.

**Comment by emsellem** [comment]
Will close as this is a broader issue which is basically to make the final reduction and mosaicking work with pointings.
